feature/issue claim from unsigned claim data
energywebfoundation/ew-did-registry pull request #309
Opened 2021-05-13 11:03 UTC by JGiter

### Summary
|             |   |
|-------------|---|
| Description | As there are no more requirements on claim requester, claim can be issued from row claim data without signing it. 
| Jira issue  |  |

2021-05-13 12:06 UTC, jrhender reviewed
I'm not understanding the PR based on the file changes. It looks like the change is to only accept a jwt `token` instead of possibly `IPublicClaim`? But I'm not sure what that has to do with
>claim can be issued from row claim data without signing it.

2021-05-13 14:24 UTC, JGiter commented
Purpose of this change is to free requester from signing claim before submitting to issuer. I've updated doc comment

2021-05-13 15:35 UTC, jrhender requested changes
Makes sense now, thanks. Could you please add a test which covers this scenario?

2021-05-13 15:35 UTC, jrhender commented on packages/claims/src/claimsIssuer/claimsIssuer.ts
> +   * specified as signed or unsinged claim
Minor typo
```suggestion
   * specified as signed or unsigned claim
```

2021-05-13 15:35 UTC, jrhender commented on packages/claims/src/claimsIssuer/claimsIssuer.ts
> +  async issuePublicClaim(claim: string | IPublicClaim): Promise<string> {
Could you please add a test which issues a claim using `IPublicClaim`?

2021-05-14 11:42 UTC, jrhender approved these changes
Looks good to me

2021-05-18 15:11 UTC, merged

2021-09-30 13:13 UTC, knzeng-e commented
:tada: This PR is included in version 0.6.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/ew-did-registry/v/0.6.0)
- [GitHub release](https://github.com/energywebfoundation/ew-did-registry/releases/tag/v0.6.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: